name: pytorch_sac_ae
channels:
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - torchvision
  - cudatoolkit=9.2
  - absl-py
  - pyparsing
  - gym=0.19.0
  - pip:
    - termcolor
    # - git+git://github.com/deepmind/dm_control.git these are installed locally now since they had to be modified
    # - git+git://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
